### ISSUE TITLE
project status / ways to get involved?

### ISSUE THREAD

**Issue by mhuesch** [plundering/plunder-reference#1]
hi! was pointed to this by someone on Urbit. have been digging into Urbit in the past 1.5ish months after spending a while around other distributed systems / p2p projects.

find the [contrasts w/ Urbit](https://github.com/plundering/plunder-reference#plunder-and-urbit) compelling and it aligns with some of the limitations of Urbit I've noticed.

it also helps that I've been Haskelling for a while so am more easily nerd sniped by Haskell specs/code.

curious what the state of the project is, and whether there is room for contributors?

if you prefer private correspondence, my email is https://www.mhueschen.space/contact.html

thx 🙏

**Comment by plundering** [comment]
Hi Michael.

The project is active. 

Right now, it's just two people hacking on a private repo, but development will soon move to this repo (after the next release, which is coming out soon).

There is definitely room for contributors, even before the release.

We are currently working towards getting a couple of real applications working: network-chat and tag-search against a large image database.

Plunder still far less mature than Urbit, but I expect it to explode once the foundations are fleshed out.  Because our architecture is compatible with the ML/Haskell paradigms, we should be able to just wholesale port significant libraries and applications.

Most of the hard research problems are solved, but there are a few still in flight:

- Nail down our strategy for migrations and build tooling for that.

- Add a type system to Sire using the approach taken by Typed Racket.

- Port Elm to Plunder (but with Rex syntax).

Outside of those core problems, basically the whole world needs to be ported, so there's near-infinite work to do.  The easiest things being little libraies uuid, sha256, map, set, parsec, etc.

----

I'm donlyd-rapwes on Urbit atm, I messaged you there.

**Comment by mhuesch** [comment]
for public context, we've been corresponding privately, so I'll close this issue.
